### ISSUE TITLE
Fails with react 0.14.0-rc1

### ISSUE THREAD

**Issue by floriancargoet** [gianu/react-fittext#10]
ReactFittext doesn't work with the latest react version (`0.14.0-rc1`).
Here's the code and error messages:

**package.json**:
``` json
  "dependencies": {
    "react": "^0.14.0-rc1",
    "react-dom": "^0.14.0-rc1",
    "react-fittext": "0.0.5"
  }
```

**main.jsx**:
``` jsx
import React from 'react';
import ReactDOM from 'react-dom';
import ReactFitText from 'react-fittext';

const el = document.getElementById('root');

ReactDOM.render(
  <ReactFitText>
    <h1>hello</h1>
  </ReactFitText>,
  el
);
```

**Console messages**:
```
Warning: Failed propType: Invalid prop `children` supplied to `ReactFitText`, expected a ReactElement.
Warning: ReactFitText(...): React component classes must extend React.Component.
Uncaught TypeError: Cannot read property 'firstChild' of undefined
```

**Comment by gianu** [comment]
@floriancargoet I just published a new version of react-fittext (version 0.1.1) with support to react 0.14-rc1. 

The new example is here: http://softwarepsychonaut.com/react-fittext/

Also, if you fork the project you can run

```
npm install
gulp dev
```

and see the same demo working on localhost:8080

Please let me know if this fix works for you.

**Comment by floriancargoet** [comment]
It works! Thanks.

**Comment by spaceghostu** [comment]
I am getting this error with react@15.4.1 and react-textfit@0.1.8
