### ISSUE TITLE
fit input boxes too!

### ISSUE THREAD

**Issue by acornejo** [gianu/react-fittext#12]
what about making inputs fit to width?

i've seen tons of apps that do this, most frequently to enter dollar amounts. If you type a single character the font is huge, and as you type more characters the size decreases.

do you think this plugin is suitable for this, or is it a completely different problem?

**Comment by gianu** [comment]
@acornejo The idea of this particular component is to only make text big, not other html elements. That being said, it shouldn't be that hard to fork this project and make it work with inputs.
