### ISSUE TITLE
Compatibility with React v15

### ISSUE THREAD

**Issue by ratson** [gianu/react-fittext#16]
The `package.json` requires `react@~0.13.x`.

Is there anything blocking from using a more recent version of `react`?

**Comment by fkrauthan** [comment]
I am running it with version 15 and besides a warning where I am not sure if its coming this plugin I do not have any issues. Can you please publish a version that marks it as ok for v15. I can't use shrinkwrap at the moment since I have a unmet peer dependency

**Comment by brettdewoody** [comment]
@fkrauthan - have you tested it in Safari? I'm getting an error with `react@15.2.1`.

**Comment by fkrauthan** [comment]
@brettdewoody I am running react 15.1.0. And tested with Chrome and Safari and Firefox

**Comment by ambethia** [comment]
I don't know if it's related, but I get:

`ReactFitText.js:45 Uncaught TypeError: Cannot set property 'fontSize' of undefined`

With React 15.2.1

**Comment by joadr** [comment]
Sent a pull Request as no error reported with react 15 and up. #18

**Comment by denis-sokolov** [comment]
Version 1.0.0 with React 15 support released!
